name: vaccine
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  ## Main packages Helper
  flutter_screenutil: ^5.0.1+3
  get: ^4.6.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  mapbox_gl: ^0.14.0
  dio: ^4.0.4
  shared_preferences: ^2.0.13

  ## UI helper
  lottie: ^1.2.1
  flutter_svg: ^1.0.0
  font_awesome_flutter: ^9.2.0
  bottom_navy_bar: ^6.0.0
  snapping_sheet: ^3.1.0
  dropdown_search: ^2.0.1
  syncfusion_flutter_charts: ^19.4.40

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  build_runner: ^2.1.7

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/icons/
    - assets/images/
    - assets/animation/
