List<String> stateList = [
  "Aceh",
  "Bali",
  "Banten",
  "Bengkulu",
  "DKI Yogyakarta",
  "DKI Jakarta",
  "Gorontalo",
  "Jambi",
  "Jawa Barat",
  "Jawa Tengah",
  "Jawa Timur",
  "Kalimantan Barat",
  "Kalimantan Selatan",
  "Kalimantan Tengah",
  "Kalimantan Timur",
  "Kalimantan Utara",
  "Kepulauan Bangka Belitung",
  "Kepulauan Riau",
  "Lampung",
  "Maluku",
  "Maluku Utara",
  "Nusa Tenggara Barat",
  "Nusa Tenggara Timur",
  "Papua",
  "Papua Barat",
  "Riau",
  "Sulawesi Barat",
  "Sulawesi Selatan",
  "Sulawesi Tengah",
  "Sulawesi Tenggara",
  "Sulawesi Utara",
  "Sumatera Barat",
  "Sumatera Selatan",
  "Sumatera Utara"
];

List<String> cityList = [
  "Aceh Barat",
  "Aceh Barat Daya",
  "Aceh Besar",
  "Aceh Jaya",
  "Aceh Selatan",
  "Aceh Singkil",
  "Aceh Tamiang",
  "Aceh Tengah",
  "Aceh Tenggara",
  "Aceh Timur",
  "Aceh Utara",
  "Agam",
  "Alor",
  "Ambon",
  "Asahan",
  "Asmat",
  "Batam",
  "Badung",
  "Balangan",
  "Balikpapan",
  "Banda Aceh",
  "Bandar Lampung",
  "Bandung",
  "Bandung Barat",
  "Banggai",
  "Banggai Kepulauan",
  "Bangka",
  "Bangka Barat",
  "Bangka Selatan",
  "Bangka Tengah",
  "Bangkalan",
  "Bangli",
  "Banjar",
  "Banjar Baru",
  "Banjarmasin",
  "Banjarnegara",
  "Bantaeng",
  "Bantul",
  "Banyu Asin",
  "Banyumas",
  "Banyuwangi",
  "Barito Kuala",
  "Barito Selatan",
  "Barito Timur",
  "Barito Utara",
  "Barru",
  "Baru",
  "Batang",
  "Batang Hari",
  "Batu",
  "Batu Bara",
  "Baubau",
  "Bekasi",
  "Belitung",
  "Belitung Timur",
  "Belu",
  "Bener Meriah",
  "Bengkalis",
  "Bengkayang",
  "Bengkulu",
  "Bengkulu Selatan",
  "Bengkulu Tengah",
  "Bengkulu Utara",
  "Berau",
  "Biak Numfor",
  "Bima",
  "Binjai",
  "Bintan",
  "Bireuen",
  "Bitung",
  "Blitar",
  "Blora",
  "Boalemo",
  "Bogor",
  "Bojonegoro",
  "Bolaang Mongondow",
  "Bolaang Mongondow Selatan",
  "Bolaang Mongondow Timur",
  "Bolaang Mongondow Utara",
  "Bombana",
  "Bondowoso",
  "Bone",
  "Bone Bolango",
  "Bontang",
  "Boven Digoel",
  "Boyolali",
  "Brebes",
  "Bukittinggi",
  "Buleleng",
  "Bulukumba",
  "Bulungan",
  "Bungo",
  "Buol",
  "Buru",
  "Buru Selatan",
  "Buton",
  "Buton Utara",
  "Ciamis",
  "Cianjur",
  "Cilacap",
  "Cilegon",
  "Cimahi",
  "Cirebon",
  "Dumai",
  "Dairi",
  "Deiyai",
  "Deli Serdang",
  "Demak",
  "Denpasar",
  "Depok",
  "Dharmasraya",
  "Dogiyai",
  "Dompu",
  "Donggala",
  "Empat Lawang",
  "Ende",
  "Enrekang",
  "Fakfak",
  "Flores Timur",
  "Garut",
  "Gayo Lues",
  "Gianyar",
  "Gorontalo",
  "Gorontalo Utara",
  "Gowa",
  "Gresik",
  "Grobogan",
  "Gunung Kidul",
  "Gunung Mas",
  "Gunungsitoli",
  "Halmahera Barat",
  "Halmahera Selatan",
  "Halmahera Tengah",
  "Halmahera Timur",
  "Halmahera Utara",
  "Hulu Sungai Selatan",
  "Hulu Sungai Tengah",
  "Hulu Sungai Utara",
  "Humbang Hasundutan",
  "Indragiri Hilir",
  "Indragiri Hulu",
  "Indramayu",
  "Intan Jaya",
  "Jakarta Barat",
  "Jakarta Pusat",
  "Jakarta Selatan",
  "Jakarta Timur",
  "Jakarta Utara",
  "Jambi",
  "Jayapura",
  "Jayawijaya",
  "Jember",
  "Jembrana",
  "Jeneponto",
  "Jepara",
  "Jombang",
  "Kaimana",
  "Kampar",
  "Kapuas",
  "Kapuas Hulu",
  "Karang Asem",
  "Karanganyar",
  "Karawang",
  "Karimun",
  "Karo",
  "Katingan",
  "Kaur",
  "Kayong Utara",
  "Kebumen",
  "Kediri",
  "Keerom",
  "Kendal",
  "Kendari",
  "Kepahiang",
  "Kepulauan Anambas",
  "Kepulauan Aru",
  "Kepulauan Mentawai",
  "Kepulauan Meranti",
  "Kepulauan Sangihe",
  "Kepulauan Selayar",
  "Kepulauan Seribu",
  "Kepulauan Sula",
  "Kepulauan Talaud",
  "Kepulauan Yapen",
  "Kerinci",
  "Ketapang",
  "Klaten",
  "Klungkung",
  "Kolaka",
  "Kolaka Utara",
  "Konawe",
  "Konawe Selatan",
  "Konawe Utara",
  "Kotamobagu",
  "Kotawaringin Barat",
  "Kotawaringin Timur",
  "Kuantan Singingi",
  "Kubu Raya",
  "Kudus",
  "Kulon Progo",
  "Kuningan",
  "Kupang",
  "Kutai Barat",
  "Kutai Kartanegara",
  "Kutai Timur",
  "Labuhan Batu",
  "Labuhan Batu Selatan",
  "Labuhan Batu Utara",
  "Lahat",
  "Lamandau",
  "Lamongan",
  "Lampung Barat",
  "Lampung Selatan",
  "Lampung Tengah",
  "Lampung Timur",
  "Lampung Utara",
  "Landak",
  "Langkat",
  "Langsa",
  "Lanny Jaya",
  "Lebak",
  "Lebong",
  "Lembata",
  "Lhokseumawe",
  "Lima Puluh Kota",
  "Lingga",
  "Lombok Barat",
  "Lombok Tengah",
  "Lombok Timur",
  "Lombok Utara",
  "Lubuklinggau",
  "Lumajang",
  "Luwu",
  "Luwu Timur",
  "Luwu Utara",
  "Madiun",
  "Magelang",
  "Magetan",
  "Majalengka",
  "Majene",
  "Makassar",
  "Malang",
  "Malinau",
  "Maluku Barat Daya",
  "Maluku Tengah",
  "Maluku Tenggara",
  "Maluku Tenggara Barat",
  "Mamasa",
  "Mamberamo Raya",
  "Mamberamo Tengah",
  "Mamuju",
  "Mamuju Utara",
  "Manado",
  "Mandailing Natal",
  "Manggarai",
  "Manggarai Barat",
  "Manggarai Timur",
  "Manokwari",
  "Mappi",
  "Maros",
  "Mataram",
  "Maybrat",
  "Medan",
  "Melawi",
  "Merangin",
  "Merauke",
  "Mesuji",
  "Metro",
  "Mimika",
  "Minahasa",
  "Minahasa Selatan",
  "Minahasa Tenggara",
  "Minahasa Utara",
  "Mojokerto",
  "Morowali",
  "Muara Enim",
  "Muaro Jambi",
  "Mukomuko",
  "Muna",
  "Murung Raya",
  "Musi Banyuasin",
  "Musi Rawas",
  "Nabire",
  "Nagan Raya",
  "Nagekeo",
  "Natuna",
  "Nduga",
  "Ngada",
  "Nganjuk",
  "Ngawi",
  "Nias",
  "Nias Barat",
  "Nias Selatan",
  "Nias Utara",
  "Nunukan",
  "Ogan Ilir",
  "Ogan Komering Ilir",
  "Ogan Komering Ulu",
  "Ogan Komering Ulu Selatan",
  "Ogan Komering Ulu Timur",
  "Pacitan",
  "Padang",
  "Padang Lawas",
  "Padang Lawas Utara",
  "Padang Panjang",
  "Padang Pariaman",
  "Padangsidimpuan",
  "Pagar Alam",
  "Pakpak Bharat",
  "Palangka Raya",
  "Palembang",
  "Palopo",
  "Palu",
  "Pamekasan",
  "Pandeglang",
  "Pangandaran",
  "Pangkajene Dan Kepulauan",
  "Pangkal Pinang",
  "Paniai",
  "Parepare",
  "Pariaman",
  "Parigi Moutong",
  "Pasaman",
  "Pasaman Barat",
  "Paser",
  "Pasuruan",
  "Pati",
  "Payakumbuh",
  "Pegunungan Bintang",
  "Pekalongan",
  "Pekanbaru",
  "Pelalawan",
  "Pemalang",
  "Pematang Siantar",
  "Penajam Paser Utara",
  "Pesawaran",
  "Pesisir Barat",
  "Pesisir Selatan",
  "Pidie",
  "Pidie Jaya",
  "Pinrang",
  "Pohuwato",
  "Polewali Mandar",
  "Ponorogo",
  "Pontianak",
  "Poso",
  "Prabumulih",
  "Pringsewu",
  "Probolinggo",
  "Pulang Pisau",
  "Pulau Morotai",
  "Puncak",
  "Puncak Jaya",
  "Purbalingga",
  "Purwakarta",
  "Purworejo",
  "Raja Ampat",
  "Rejang Lebong",
  "Rembang",
  "Rokan Hilir",
  "Rokan Hulu",
  "Rote Ndao",
  "Siak",
  "Sabang",
  "Sabu Raijua",
  "Salatiga",
  "Samarinda",
  "Sambas",
  "Samosir",
  "Sampang",
  "Sanggau",
  "Sarmi",
  "Sarolangun",
  "Sawah Lunto",
  "Sekadau",
  "Seluma",
  "Semarang",
  "Seram Bagian Barat",
  "Seram Bagian Timur",
  "Serang",
  "Serdang Bedagai",
  "Seruyan",
  "Siau Tagulandang Biaro",
  "Sibolga",
  "Sidenreng Rappang",
  "Sidoarjo",
  "Sigi",
  "Sijunjung",
  "Sikka",
  "Simalungun",
  "Simeulue",
  "Singkawang",
  "Sinjai",
  "Sintang",
  "Situbondo",
  "Sleman",
  "Solok",
  "Solok Selatan",
  "Soppeng",
  "Sorong",
  "Sorong Selatan",
  "Sragen",
  "Subang",
  "Subulussalam",
  "Sukabumi",
  "Sukamara",
  "Sukoharjo",
  "Sumba Barat",
  "Sumba Barat Daya",
  "Sumba Tengah",
  "Sumba Timur",
  "Sumbawa",
  "Sumbawa Barat",
  "Sumedang",
  "Sumenep",
  "Sungai Penuh",
  "Supiori",
  "Surabaya",
  "Surakarta",
  "Tabalong",
  "Tabanan",
  "Takalar",
  "Tambrauw",
  "Tana Tidung",
  "Tana Toraja",
  "Tanah Bumbu",
  "Tanah Datar",
  "Tanah Laut",
  "Tangerang",
  "Tangerang Selatan",
  "Tanggamus",
  "Tanjung Balai",
  "Tanjung Jabung Barat",
  "Tanjung Jabung Timur",
  "Tanjung Pinang",
  "Tapanuli Selatan",
  "Tapanuli Tengah",
  "Tapanuli Utara",
  "Tapin",
  "Tarakan",
  "Tasikmalaya",
  "Tebing Tinggi",
  "Tebo",
  "Tegal",
  "Teluk Bintuni",
  "Teluk Wondama",
  "Temanggung",
  "Ternate",
  "Tidore Kepulauan",
  "Timor Tengah Selatan",
  "Timor Tengah Utara",
  "Toba Samosir",
  "Tojo Una-una",
  "Toli-toli",
  "Tolikara",
  "Tomohon",
  "Toraja Utara",
  "Trenggalek",
  "Tual",
  "Tuban",
  "Tulang Bawang Barat",
  "Tulangbawang",
  "Tulungagung",
  "Wajo",
  "Wakatobi",
  "Waropen",
  "Way Kanan",
  "Wonogiri",
  "Wonosobo",
  "Yahukimo",
  "Yalimo",
  "Yogyakarta"
];

List<String> districtList = [
  "2 X 11 Enam Lingkung",
  "2 X 11 Kayu Tanam",
  "Abab",
  "Abang",
  "Abeli",
  "Abenaho",
  "Abepura",
  "Abiansemal",
  "Aboy",
  "Abuki",
  "Abun",
  "Abung  Kunang",
  "Abung Barat",
  "Abung Pekurun",
  "Abung Selatan",
  "Abung Semuli",
  "Abung Surakarta",
  "Abung Tengah",
  "Abung Timur",
  "Abung Tinggi",
  "Adi Luwih",
  "Adian Koting",
  "Adimulyo",
  "Adipala",
  "Adiwerna",
  "Adonara",
  "Adonara Barat",
  "Adonara Tengah",
  "Adonara Timur",
  "Aek Bilah",
  "Aek Kuasan",
  "Aek Kuo",
  "Aek Ledong",
  "Aek Nabara Barumun",
  "Aek Natas",
  "Aek Songsongan",
  "Aere",
  "Aertembaga",
  "Aesesa",
  "Aesesa Selatan",
  "Afulu",
  "Agadugume",
  "Agats",
  "Agimuga",
  "Agisiga",
  "Agrabinta",
  "Agung",
  "Agung Barat",
  "Agung Timur",
  "Aifat",
  "Aifat Selatan",
  "Aifat Timur",
  "Aifat Timur Jauh",
  "Aifat Timur Selatan",
  "Aifat Timur Tengah",
  "Aifat Utara",
  "Aikmel",
  "Aimando Padaido",
  "Aimas",
  "Aimere",
  "Air Batu",
  "Air Besar",
  "Air Besi",
  "Air Buaya",
  "Air Dikit",
  "Air Garam",
  "Air Gegas",
  "Air Hangat",
  "Air Hangat Barat",
  "Air Hangat Timur",
  "Air Hitam",
  "Air Joman",
  "Air Kumbang",
  "Air Manjunto",
  "Air Naningan",
  "Air Napal",
  "Air Nipis",
  "Air Padang",
  "Air Periukan",
  "Air Putih",
  "Air Rami",
  "Air Saleh",
  "Air Sugihan",
  "Air Upas",
  "Airmadidi",
  "Airu",
  "Aitinyo",
  "Aitinyo Barat/athabu",
  "Aitinyo Raya",
  "Aitinyo Tengah",
  "Aitinyo Utara",
  "Ajangale",
  "Ajibarang",
  "Ajibata",
  "Ajung",
  "Akabiluru",
  "Akat",
  "Alafan",
  "Alak",
  "Alalak",
  "Alang Alang Lebar",
  "Alas",
  "Alas Barat",
  "Alasa",
  "Alasa Talu Muzoi",
  "Alemsom",
  "Alian",
  "Alla",
  "Alok",
  "Alok Barat",
  "Alok Timur",
  "Alor Barat Daya",
  "Alor Barat Laut",
  "Alor Selatan",
  "Alor Tengah Utara",
  "Alor Timur",
  "Alor Timur Laut",
  "Alu",
  "Aluh - Aluh",
  "Amabi Oefeto",
  "Amabi Oefeto Timur",
  "Amahai",
  "Amalatu",
  "Amali",
  "Amanatun Selatan",
  "Amanatun Utara",
  "Amandraya",
  "Amanuban Barat",
  "Amanuban Selatan",
  "Amanuban Tengah",
  "Amanuban Timur",
  "Amarasi",
  "Amarasi Barat",
  "Amarasi Selatan",
  "Amarasi Timur",
  "Ambal",
  "Ambalau",
  "Ambalawi",
  "Ambarawa",
  "Ambatkwi",
  "Amberbaken",
  "Ambulu",
  "Ambunten",
  "Amen",
  "Amfoang Barat Daya",
  "Amfoang Barat Laut",
  "Amfoang Selatan",
  "Amfoang Tengah",
  "Amfoang Timur",
  "Amfoang Utara",
  "Amonggedo",
  "Ampana Kota",
  "Ampana Tete",
  "Ampek Angkek",
  "Ampek Nagari",
  "Ampel",
  "Ampelgading",
  "Ampenan",
  "Ampibabo",
  "Amuma",
  "Amuntai Selatan",
  "Amuntai Tengah",
  "Amuntai Utara",
  "Amurang",
  "Amurang Barat",
  "Amurang Timur",
  "Anak Ratu Aji",
  "Anak Tuha",
  "Andam Dewi",
  "Andey",
  "Andir",
  "Andong",
  "Andoolo",
  "Andowia",
  "Angata",
  "Anggaberi",
  "Anggana",
  "Anggeraja",
  "Anggi",
  "Anggi Gida",
  "Anggrek",
  "Anggruk",
  "Angkaisera",
  "Angkinang",
  "Angkola  Barat",
  "Angkola Sangkunur",
  "Angkola Selatan",
  "Angkola Timur",
  "Angkona",
  "Angsana",
  "Animha",
  "Anjatan",
  "Anjir Muara",
  "Anjir Pasar",
  "Anjongan",
  "Anreapi",
  "Antang Kalang",
  "Antapani",
  "Anyar",
  "Apalapsili",
  "Apawer Hulu",
  "Aradide",
  "Arahan",
  "Aralle",
  "Aramo",
  "Aranday",
  "Aranio",
  "Arcamanik",
  "Arga Makmur",
  "Argapura",
  "Argomulyo",
  "Arimop",
  "Arjasa",
  "Arjasari",
  "Arjawinangun",
  "Arjosari",
  "Arma Jaya",
  "Aroba",
  "Arongan Lambalek",
  "Arosbaya",
  "Arse",
  "Arso",
  "Arso Timur",
  "Aru Selatan",
  "Aru Selatan Timur",
  "Aru Tengah",
  "Aru Tengah Selatan",
  "Aru Tengah Timur",
  "Aru Utara",
  "Arungkeke",
  "Arut Selatan",
  "Arut Utara",
  "Asakota",
  "Asam Jujuhan",
  "Asembagus",
  "Asemrowo",
  "Asera",
  "Asinua",
  "Asologaima",
  "Asolokobal",
  "Asparaga",
  "Assue",
  "Astambul",
  "Astanaanyar",
  "Astanajapura",
  "Atadei",
  "Atambua",
  "Atambua Barat",
  "Atambua Selatan",
  "Atinggola",
  "Atsy",
  "Atu Lintang",
  "Aur Birugo Tigo Baleh",
  "Awan Rante Karua",
  "Awang",
  "Awangpone",
  "Awayan",
  "Awinbon",
  "Ayah",
  "Ayamaru",
  "Ayamaru Barat",
  "Ayamaru Jaya",
  "Ayamaru Selatan",
  "Ayamaru Selatan Jaya",
  "Ayamaru Tengah",
  "Ayamaru Timur",
  "Ayamaru Timur Selatan",
  "Ayamaru Utara",
  "Ayamaru Utara Timur",
  "Ayau",
  "B U L O",
  "Baamang",
  "Babadan",
  "Babah Rot",
  "Babakan",
  "Babakan Ciparay",
  "Babakan Madang",
  "Babakancikao",
  "Babalan",
  "Babar Timur",
  "Babat",
  "Babat Supat",
  "Babat Toman",
  "Babelan",
  "Babirik",
  "Babo",
  "Babul Makmur",
  "Babul Rahmad",
  "Babulu",
  "Babussalam",
  "Bacan",
  "Bacan Barat",
  "Bacan Barat Utara",
  "Bacan Selatan",
  "Bacan Timur",
  "Bacan Timur Selatan",
  "Bacan Timur Tengah",
  "Bacukiki",
  "Bacukiki Barat",
  "Badar",
  "Badas",
  "Badau",
  "Badegan",
  "Badiri",
  "Bae",
  "Baebunta",
  "Bagan Sinembah",
  "Bagelen",
  "Bagor",
  "Bahagia",
  "Bahar Selatan",
  "Bahar Utara",
  "Baharu",
  "Bahau Hulu",
  "Bahodopi",
  "Bahuga",
  "Baito",
  "Baiturrahman",
  "Baitussalam",
  "Bajawa",
  "Bajawa Utara",
  "Bajeng",
  "Bajeng Barat",
  "Bajenis",
  "Bajo",
  "Bajo Barat",
  "Bajubang",
  "Bajuin",
  "Bakam",
  "Bakarangan",
  "Bakauheni",
  "Baki",
  "Bakongan",
  "Bakongan Timur",
  "Bakti Raja",
  "Baktiya",
  "Baktiya Barat",
  "Bakumpai",
  "Bakung",
  "Balabalakang",
  "Balaesang",
  "Balaesang Tanjung",
  "Balai",
  "Balai Riam",
  "Balanipa",
  "Balantak",
  "Balantak Selatan",
  "Balantak Utara",
  "Balapulang",
  "Balaraja",
  "Baleendah",
  "Balen",
  "Balerejo",
  "Balige",
  "Balik Bukit",
  "Balikpapan Barat",
  "Balikpapan Selatan",
  "Balikpapan Tengah",
  "Balikpapan Timur",
  "Balikpapan Utara",
  "Balingga",
  "Balinggi",
  "Balla",
  "Balocci",
  "Balong",
  "Balong Bendo",
  "Balongan",
  "Balongpanggang",
  "Balung",
  "Balusu",
  "Bambaira",
  "Bambalamotu",
  "Bambang",
  "Bambang Lipuro",
  "Bambel",
  "Banama Tingang",
  "Banawa",
  "Banawa Selatan",
  "Banawa Tengah",
  "Bancak",
  "Bancar",
  "Banda",
  "Banda Alam",
  "Banda Baro",
  "Banda Mulia",
  "Banda Raya",
  "Banda Sakti",
  "Bandar",
  "Bandar Baru",
  "Bandar Dua",
  "Bandar Huluan",
  "Bandar Kedung Mulyo",
  "Bandar Khalipah",
  "Bandar Masilam",
  "Bandar Mataram",
  "Bandar Negeri Semuong",
  "Bandar Negeri Suoh",
  "Bandar Pasir Mandoge",
  "Bandar Petalangan",
  "Bandar Pulau",
  "Bandar Pusaka",
  "Bandar Seikijang",
  "Bandar Sribawono",
  "Bandar Surabaya",
  "Banding Agung",
  "Bandongan",
  "Bandung",
  "Bandung Kidul",
  "Bandung Kulon",
  "Bandung Wetan",
  "Bandungan",
  "Bang Haji",
  "Banggae",
  "Banggae Timur",
  "Banggai",
  "Banggai Selatan",
  "Banggai Tengah",
  "Banggai Utara",
  "Bangil",
  "Bangilan",
  "Bangkala",
  "Bangkala Barat",
  "Bangkalan",
  "Bangkinang",
  "Bangkinang Seberang",
  "Bangko",
  "Bangko Barat",
  "Bangko Pusako",
  "Bangkurung",
  "Bangli",
  "Bangodua",
  "Bangorejo",
  "Bangsal",
  "Bangsalsari",
  "Bangsri",
  "Bangun Purba",
  "Bangunrejo",
  "Banguntapan",
  "Banjang",
  "Banjar",
  "Banjar Agung",
  "Banjar Baru",
  "Banjar Baru Selatan",
  "Banjar Baru Utara",
  "Banjar Margo",
  "Banjaran",
  "Banjarangkan",
  "Banjarejo",
  "Banjarharjo",
  "Banjarmangu",
  "Banjarmasin Barat",
  "Banjarmasin Selatan",
  "Banjarmasin Tengah",
  "Banjarmasin Timur",
  "Banjarmasin Utara",
  "Banjarnegara",
  "Banjarsari",
  "Banjarwangi",
  "Banjit",
  "Bansari",
  "Bantaeng",
  "Bantan",
  "Bantaran",
  "Bantarbolang",
  "Bantargadung",
  "Bantargebang",
  "Bantarkalong",
  "Bantarkawung",
  "Bantarsari",
  "Bantarujeg",
  "Bantimurung",
  "Bantul",
  "Bantur",
  "Banua Lawas",
  "Banuhampu",
  "Banyakan",
  "Banyu Urip",
  "Banyuanyar",
  "Banyuasin I",
  "Banyuasin Ii",
  "Banyuasin Iii",
  "Banyuates",
  "Banyubiru",
  "Banyudono",
  "Banyuglugur",
  "Banyuke Hulu",
  "Banyumanik",
  "Banyumas",
  "Banyuputih",
  "Banyuresmi",
  "Banyusari",
  "Banyuwangi",
  "Baolan",
  "Bara",
  "Barabai",
  "Baradatu",
  "Baraka",
  "Barambai",
  "Barangin",
  "Barangka",
  "Baranti",
  "Baras",
  "Barat",
  "Barebbo",
  "Baregbeg",
  "Bareng",
  "Barito Tuhup Raya",
  "Baroko",
  "Barombong",
  "Baron",
  "Barong Tongkok",
  "Baros",
  "Barru",
  "Baru",
  "Baruga",
  "Barumun",
  "Barumun Selatan",
  "Barumun Tengah",
  "Baruppu",
  "Barus",
  "Barus Utara",
  "Barusjahe",
  "Basa Ampek Balai Tapan",
  "Basala",
  "Basarang",
  "Basidondo",
  "Baso",
  "Bassesangtempe",
  "Bassesangtempe Utara",
  "Bata Bual",
  "Bataguh",
  "Batahan",
  "Batalaiworu",
  "Batam Kota",
  "Batang",
  "Batang Alai Selatan",
  "Batang Alai Timur",
  "Batang Alai Utara",
  "Batang Anai",
  "Batang Angkola",
  "Batang Asai",
  "Batang Asam",
  "Batang Batang",
  "Batang Cenaku",
  "Batang Gansal",
  "Batang Gasan",
  "Batang Kapas",
  "Batang Kuis",
  "Batang Lomang",
  "Batang Lubu Sutam",
  "Batang Lupar",
  "Batang Masumai",
  "Batang Merangin",
  "Batang Natal",
  "Batang Onang",
  "Batang Peranap",
  "Batang Serangan",
  "Batang Toru",
  "Batang Tuaka",
  "Batangan",
  "Batanghari",
  "Batanghari Leko",
  "Batanghari Nuban",
  "Batangkawa",
  "Batani",
  "Batanta Selatan",
  "Batanta Utara",
  "Batauga",
  "Batealit",
  "Batee",
  "Bathin Ii Babeko",
  "Bathin Ii Pelayang",
  "Bathin Iii",
  "Bathin Iii Ulu",
  "Bathin Viii",
  "Bati - Bati",
  "Batik Nau",
  "Batin Xxiv",
  "Batipuh",
  "Batipuh Selatan",
  "Batom",
  "Batu",
  "Batu Aji",
  "Batu Ampar",
  "Batu Atas",
  "Batu Benawa",
  "Batu Brak",
  "Batu Engau",
  "Batu Hampar",
  "Batu Ketulis",
  "Batu Layar",
  "Batu Licin",
  "Batu Mandi",
  "Batu Marmar",
  "Batu Putih",
  "Batu Raja Barat",
  "Batu Raja Timur",
  "Batu Sopang",
  "Batuan",
  "Batuceper",
  "Batudaa",
  "Batudaa Pantai",
  "Batui",
  "Batui Selatan",
  "Batujajar",
  "Batujaya",
  "Batukara",
  "Batukliang",
  "Batukliang Utara",
  "Batulanteh",
  "Batulappa",
  "Batununggal",
  "Batupoaro",
  "Batuputih",
  "Batur",
  "Baturetno",
  "Baturiti",
  "Baturraden",
  "Batuwarno",
  "Baula",
  "Baureno",
  "Bawang",
  "Bawen",
  "Bawolato",
  "Bayah",
  "Bayan",
  "Bayang",
  "Bayat",
  "Bayongbong",
  "Bayung Lencir",
  "Bebandem",
  "Beber",
  "Bebesen",
  "Beduwai",
  "Bejen",
  "Beji",
  "Bekasi Barat",
  "Bekasi Selatan",
  "Bekasi Timur",
  "Bekasi Utara",
  "Bekri",
  "Belakang Padang",
  "Belalau",
  "Belang",
  "Belantikan Raya",
  "Belawa",
  "Belawang",
  "Belida Darat",
  "Belik",
  "Belimbing",
  "Belimbing Hulu",
  "Belinyu",
  "Belitang",
  "Belitang Hilir",
  "Belitang Hulu",
  "Belitang Ii",
  "Belitang Iii",
  "Belitang Jaya",
  "Belitang Madang Raya",
  "Belitang Mulya",
  "Belo",
  "Belopa",
  "Belopa Utara",
  "Benai",
  "Benakat",
  "Benawa",
  "Benda",
  "Bendahara",
  "Bendo",
  "Bendosari",
  "Bendungan",
  "Bener",
  "Bener Kelipah",
  "Bengalon",
  "Bengkalis",
  "Bengkayang",
  "Bengkelekila",
  "Bengkong",
  "Bengkunat",
  "Bengkunat Belimbing",
  "Bengo",
  "Benjeng",
  "Benowo",
  "Benteng",
  "Bentian Besar",
  "Benua",
  "Benua Kayong",
  "Benua Lima",
  "Benuki",
  "Beo",
  "Beo Selatan",
  "Beo Utara",
  "Beoga",
  "Berampu",
  "Berastagi",
  "Beraur",
  "Berbah",
  "Berbak",
  "Berbek",
  "Bergas",
  "Beringin",
  "Bermani Ilir",
  "Bermani Ulu",
  "Bermani Ulu Raya",
  "Beruntung Baru",
  "Besi",
  "Besitang",
  "Besuk",
  "Besuki",
  "Besulutu",
  "Betara",
  "Betoambari",
  "Betung",
  "Beutong",
  "Beutong Ateuh Banggalang",
  "Bewani",
  "Biak Barat",
  "Biak Kota",
  "Biak Timur",
  "Biak Utara",
  "Biandoga",
  "Biaro",
  "Biatan",
  "Biau",
  "Bibida",
  "Biboki Anleu",
  "Biboki Feotleu",
  "Biboki Moenleu",
  "Biboki Selatan",
  "Biboki Tanpah",
  "Biboki Utara",
  "Biduk Biduk",
  "Bies",
  "Bika",
  "Bikomi Nilulat",
  "Bikomi Selatan",
  "Bikomi Tengah",
  "Bikomi Utara",
  "Bilah Barat",
  "Bilah Hilir",
  "Bilah Hulu",
  "Bilalang",
  "Bilato",
  "Biluhu",
  "Bime",
  "Binakal",
  "Binamu",
  "Binangun",
  "Bindu Riang",
  "Bingin Kuning",
  "Binjai",
  "Binjai Barat",
  "Binjai Hulu",
  "Binjai Kota",
  "Binjai Selatan",
  "Binjai Timur",
  "Binjai Utara",
  "Binong",
  "Binongko",
  "Bintan Pesisir",
  "Bintan Timur",
  "Bintan Utara",
  "Bintang",
  "Bintang Ara",
  "Bintang Bayu",
  "Bintauna",
  "Bintuni",
  "Binuang",
  "Birem Bayeun",
  "Biring Kanaya",
  "Biringbulu",
  "Biru-biru",
  "Biscoop",
  "Bissappu",
  "Bittuang",
  "Blado",
  "Blahbatuh",
  "Blambangan Pagar",
  "Blambangan Umpu",
  "Blanakan",
  "Blang Bintang",
  "Blang Jerango",
  "Blang Mangat",
  "Blang Pegayon",
  "Blang Pidie",
  "Blangkejeren",
  "Blega",
  "Blimbing",
  "Blora",
  "Blubur Limbangan",
  "Bluluk",
  "Bluto",
  "Boawae",
  "Bobotsari",
  "Bodeh",
  "Bogobaida",
  "Bogor Barat",
  "Bogor Selatan",
  "Bogor Tengah",
  "Bogor Timur",
  "Bogor Utara",
  "Bogorejo",
  "Bohorok",
  "Boja",
  "Bojonegara",
  "Bojonegoro",
  "Bojong",
  "Bojong Gede",
  "Bojong Genteng",
  "Bojongasih",
  "Bojonggambir",
  "Bojongloa Kaler",
  "Bojongloa Kidul",
  "Bojongmangu",
  "Bojongmanik",
  "Bojongpicung",
  "Bojongsari",
  "Bojongsoang",
  "Bokan Kepulauan",
  "Bokat",
  "Boking",
  "Bokondini",
  "Bokoneri",
  "Bola",
  "Bolaang",
  "Bolaang Timur",
  "Bolakme",
  "Bolang Itang Barat",
  "Bolang Itang Timur",
  "Bolang Uki",
  "Bolano",
  "Bolano Lambunu",
  "Boleng",
  "Boliyohuto",
  "Bolo",
  "Bomakia",
  "Bomberay",
  "Bomela",
  "Bonai Darussalam",
  "Bonang",
  "Bonatua Lunasi",
  "Bondifuar",
  "Bondoala",
  "Bondowoso",
  "Bone",
  "Bone Raya",
  "Bone-bone",
  "Bonegunu",
  "Bonehau",
  "Bonepantai",
  "Bongan",
  "Bongas",
  "Bonggakaradeng",
  "Bonggo",
  "Bonggo Timur",
  "Bongomeme",
  "Bonjol",
  "Bonorowo",
  "Bontang Barat",
  "Bontang Selatan",
  "Bontang Utara",
  "Bonti",
  "Bonto Bahari",
  "Bontoa",
  "Bontoala",
  "Bontocani",
  "Bontoharu",
  "Bontolempangan",
  "Bontomanai",
  "Bontomarannu",
  "Bontomatene",
  "Bontonompo",
  "Bontonompo Selatan",
  "Bontoramba",
  "Bontosikuyu",
  "Bontotiro",
  "Borbor",
  "Borme",
  "Borobudur",
  "Borong",
  "Bosar Maligas",
  "Botin Leobele",
  "Botolinggo",
  "Botomuzoi",
  "Botu Pingge",
  "Botumoito",
  "Bowobado",
  "Boyan Tanjung",
  "Boyolali",
  "Boyolangu",
  "Braja Slebah",
  "Bram Itam",
  "Brandan Barat",
  "Brang Ene",
  "Brang Rea",
  "Brangsong",
  "Brati",
  "Brebes",
  "Bringin",
  "Brondong",
  "Bruno",
  "Bruyadori",
  "Bua",
  "Buahbatu",
  "Buahdua",
  "Bualemo",
  "Buana Pemaca",
  "Buaran",
  "Buay  Bahuga",
  "Buay Madang",
  "Buay Madang Timur",
  "Buay Pemaca",
  "Buay Pematang Ribu Ranau Tengah",
  "Buay Pemuka Bangsa Raja",
  "Buay Pemuka Peliung",
  "Buay Rawan",
  "Buay Runjung",
  "Buay Sandang Aji",
  "Buayan",
  "Bubon",
  "Bubulan",
  "Bubutan",
  "Budong-budong",
  "Buduran",
  "Buer",
  "Bugulkidul",
  "Bukal",
  "Bukateja",
  "Buke",
  "Buki",
  "Bukik Barisan",
  "Bukit",
  "Bukit Batu",
  "Bukit Bestari",
  "Bukit Intan",
  "Bukit Kapur",
  "Bukit Kecil",
  "Bukit Kemuning",
  "Bukit Kerman",
  "Bukit Malintang",
  "Bukit Raya",
  "Bukit Santuai",
  "Bukit Sundi",
  "Bukit Tusam",
  "Buko",
  "Buko Selatan",
  "Bula",
  "Bula Barat",
  "Bulagi",
  "Bulagi Selatan",
  "Bulagi Utara",
  "Bulak",
  "Bulakamba",
  "Bulang",
  "Bulang Tengah Suku Ulu",
  "Bulango Selatan",
  "Bulango Timur",
  "Bulango Ulu",
  "Bulango Utara",
  "Bulawa",
  "Buleleng",
  "Bulik",
  "Bulik Timur",
  "Bulok",
  "Bulu",
  "Bulu Taba",
  "Bulukerto",
  "Bulukumpa",
  "Bululawang",
  "Bulupoddo",
  "Buluspesantren",
  "Bumi Agung",
  "Bumi Makmur",
  "Bumi Nabung",
  "Bumi Ratu Nuban",
  "Bumi Raya",
  "Bumi Waras",
  "Bumiaji",
  "Bumiayu",
  "Bumijawa",
  "Bunaken",
  "Bunaken Kepulauan",
  "Bunga Mas",
  "Bunga Mayang",
  "Bunga Raya",
  "Bungah",
  "Bungatan",
  "Bungaya",
  "Bungbulang",
  "Bungi",
  "Bungin",
  "Bungkal",
  "Bungku Barat",
  "Bungku Pesisir",
  "Bungku Selatan",
  "Bungku Tengah",
  "Bungku Timur",
  "Bungku Utara",
  "Bungo Dani",
  "Bungoro",
  "Bungur",
  "Bunguran Barat",
  "Bunguran Selatan",
  "Bunguran Tengah",
  "Bunguran Timur",
  "Bunguran Timur Laut",
  "Bunguran Utara",
  "Bungursari",
  "Bungus Teluk Kabung",
  "Bunobogu",
  "Bunta",
  "Buntao",
  "Buntu Batu",
  "Buntu Malangka",
  "Buntu Pane",
  "Buntu Pepasan",
  "Buntulia",
  "Bunut",
  "Bunut Hilir",
  "Bunut Hulu",
  "Bunyu",
  "Bupon",
  "Burau",
  "Burneh",
  "Buru",
  "Buruway",
  "Busang",
  "Busungbiu",
  "Butuh",
  "Buyasari",
  "Cabangbungin",
  "Cadasari",
  "Cakranegara",
  "Cakung",
  "Camba",
  "Cambai",
  "Campaka",
  "Campaka Mulya",
  "Campalagian",
  "Camplong",
  "Campur Darat",
  "Candi",
  "Candi Laras Selatan",
  "Candi Laras Utara",
  "Candimulyo",
  "Candipuro",
  "Candiroto",
  "Candisari",
  "Canduang",
  "Cangkringan",
  "Cangkuang",
  "Cantigi",
  "Capkala",
  "Carenang",
  "Caringin",
  "Carita",
  "Cariu",
  "Catubouw",
  "Cawas",
  "Celala",
  "Cempa",
  "Cempaga",
  "Cempaga Hulu",
  "Cempaka",
  "Cempaka Putih",
  "Cendana",
  "Cengal",
  "Cengkareng",
  "Cenrana",
];

List<String> countyList = [
  "Abuki",
  "Abuleta",
  "Abumbun Jaya",
  "Abung",
  "Abung Jayo",
  "Abung Surapati",
  "Aburage",
  "Aburan Batang Tebo",
  "Abusa",
  "Abusur",
  "Acango",
  "Aceh",
  "Acemo",
  "Ad Wearaur",
  "Adabai",
  "Adabang",
  "Adainasnosen",
  "Adaka Jaya",
  "Adam",
  "Adan",
  "Adan-adan",
  "Adang",
  "Adang Beurabo",
  "Adang Buom",
  "Adang Jaya",
  "Adatongeng",
  "Adaut",
  "Adauwo",
  "Adean",
  "Adi Jaya",
  "Adi Karya Mulya",
  "Adi Luhur",
  "Adi Luwih",
  "Adi Mulyo",
  "Adi Purwa",
  "Adi Warno",
  "Adian Gupa",
  "Adian Jior",
  "Adian Koting",
  "Adian Nangka",
  "Adian Torop",
  "Adiarsa",
  "Adiarsa Barat",
  "Adiarsa Timur",
  "Adidharma",
  "Adijaya",
  "Adikarso",
  "Adikarto",
  "Adil Makmur",
  "Adiluhur",
  "Adimulya",
  "Adimulyo",
  "Adin Tengah",
  "Adinuso",
  "Adipala",
  "Adipasir",
  "Adipura Kencana",
  "Adipuro",
  "Adiraja",
  "Adireja Kulon",
  "Adireja Wetan",
  "Adirejo",
  "Adisana",
  "Adisara",
  "Aditirto",
  "Adiwarno",
  "Adiwerna",
  "Adiwipi",
  "Adobala",
  "Adodo Fordata",
  "Adodomolo",
  "Adoh",
  "Adoki",
  "Adolang",
  "Adolang Dua",
  "Adolina",
  "Adona",
  "Adonara",
  "Adora",
  "Adow",
  "Adow Selatan",
  "Adu",
  "Adu Manis",
  "Aduer",
  "Aduwei",
  "Ae Ndoko",
  "Aebara",
  "Aedan Raya",
  "Aejeti",
  "Aek Badak Jae",
  "Aek Badak Julu",
  "Aek Bamban",
  "Aek Bange",
  "Aek Banir",
  "Aek Bargot",
  "Aek Baru Jae",
  "Aek Baru Julu",
  "Aek Batang Paya",
  "Aek Batu",
  "Aek Bayur",
  "Aek Bolon Jae",
  "Aek Bolon Julu",
  "Aek Bonban",
  "Aek Bottar",
  "Aek Botung",
  "Aek Buaton",
  "Aek Buru Selatan",
  "Aek Dakka",
  "Aek Gambir",
  "Aek Garingging",
  "Aek Garut",
  "Aek Ger Ger",
  "Aek Godang",
  "Aek Goti",
  "Aek Gunung",
  "Aek Guo",
  "Aek Habil",
  "Aek Haminjon",
  "Aek Haruaya",
  "Aek Haruya",
  "Aek Hitetoras",
  "Aek Holbung",
  "Aek Horsik",
  "Aek Ilung",
  "Aek Jabut",
  "Aek Jangkang",
  "Aek Kahombu",
  "Aek Kanan",
  "Aek Kanopan",
  "Aek Kanopan Timur",
  "Aek Korsik",
  "Aek Kota Batu",
  "Aek Kundur",
  "Aek Lancat",
  "Aek Latong",
  "Aek Ledong",
  "Aek Loba",
  "Aek Loba Afdeling I",
  "Aek Loba Pekan",
  "Aek Lung",
  "Aek Manggis",
  "Aek Manis",
  "Aek Manyuruk",
  "Aek Marian Mg",
  "Aek Mata",
  "Aek Mual",
  "Aek Muara Pinang",
  "Aek Nabara",
  "Aek Nabara Jae",
  "Aek Nabara Julu",
  "Aek Nabara Tonga",
  "Aek Nabuntu",
  "Aek Nadua",
  "Aek Nagali",
  "Aek Najaji",
  "Aek Nangali",
  "Aek Natas",
  "Aek Natolu Jaya",
  "Aek Nauli",
  "Aek Nauli I",
  "Aek Nauli Ii",
  "Aek Nauli Iii",
  "Aek Nauli Iv",
  "Aek Ngadol Nauli",
  "Aek Ngali",
  "Aek Paing",
  "Aek Pancur",
  "Aek Pardomuan",
  "Aek Parombunan",
  "Aek Parupuk",
  "Aek Pining",
  "Aek Raja",
  "Aek Rao Tapian Nadenggan",
  "Aek Raru",
  "Aek Raso",
  "Aek Sabaon",
  "Aek Siala",
  "Aek Sian Simun",
  "Aek Simanat",
  "Aek Simotung",
  "Aek Sipitudai",
  "Aek Sitio-tio",
  "Aek Songsongan",
  "Aek Sorik",
  "Aek Suhat",
  "Aek Suhat Jae",
  "Aek Suhat Tr",
  "Aek Sundur",
  "Aek Tampang",
  "Aek Tanduk",
  "Aek Tangga",
  "Aek Tapa",
  "Aek Teluk Kiri",
  "Aek Tiga",
  "Aek Tolang",
  "Aek Torop",
  "Aek Tuhul",
  "Aek Tunjang",
  "Aek Ulok",
  "Aek Uncim",
  "Aek Unsin",
  "Aek Urat",
  "Aekharuaya)",
  "Aelipo",
  "Aemuri",
  "Aeng Batu-batu",
  "Aeng Sareh",
  "Aeng Towa",
  "Aenganyar",
  "Aengbaja Kenek",
  "Aengbaja Raja",
  "Aengdake",
  "Aengmerah",
  "Aengpanas",
  "Aengtabar",
  "Aengtongtong",
  "Aepodu",
  "Aer Bale",
  "Aer Banua",
  "Aeramo",
  "Aere",
  "Aergale",
  "Aertembaga Dua",
  "Aertembaga Satu",
  "Aewoe",
  "Aewora",
  "Afa Afa",
  "Afang Defol",
  "Afang Kota",
  "Afd.ii Buket",
  "Afdeling I Rantauprapat",
  "Afdeling Ii Rantauprapat",
  "Afdeling Vi Dolok Ilir",
  "Afdeling Vii Dolok Ilir",
  "Afe-taduma",
  "Afia",
  "Afkab Makmur",
  "Afoan",
  "Afrawi",
  "Afuafu",
  "Afulu",
  "Agadugume",
  "Agak",
  "Agani",
  "Agapo / Widimeida",
  "Agel",
  "Agerwara",
  "Aghain",
  "Agham",
  "Agimdek",
  "Agin",
  "Agisiga",
  "Agiyome",
  "Aglik",
  "Agom",
  "Agotey",
  "Aguit",
  "Aguluntipmu",
  "Agung",
  "Agung Baru",
  "Agung Batin",
  "Agung Dalem",
  "Agung Jati",
  "Agung Jaya",
  "Agung Lawangan",
  "Agung Mulya",
  "Agung Timur",
  "Agungmulyo",
  "Agusen",
  "Aha",
  "Aha Patung",
  "Ahanari",
  "Ahedano",
  "Ahilulu",
  "Ahiolo Abio",
  "Ahu",
  "Ahuangguluri",
  "Ahuawali",
  "Ahuawatu",
  "Ahuhu",
  "Ahuloa",
  "Ai Kangkung",
  "Ai Mual",
  "Aia Angek",
  "Aia Bangih",
  "Aia Batumbuak",
  "Aia Gadang",
  "Aia Luo",
  "Aib",
  "Aiboa/epawa",
  "Aibobor",
  "Aibondeni",
  "Aibore",
  "Aibura",
  "Aie Angek",
  "Aie Dingin",
  "Aie Haji",
  "Aie Tajun Lubuk Alung",
  "Aifalim",
  "Aifam",
  "Aifo",
  "Aiga",
  "Aih Selah",
  "Aik Berik",
  "Aik Bual",
  "Aik Bukaq",
  "Aik Dareq",
  "Aik Ketekok",
  "Aik Madu",
  "Aik Mual",
  "Aik Pelempang Jaya",
  "Aik Prapa",
  "Aik Rayak",
  "Aikai",
  "Aikawapuka",
  "Aikdewa",
  "Aikima",
  "Aikmel",
  "Aikmel Barat",
  "Aikmel Timur",
  "Aikmel Utara",
  "Aikrer",
  "Aikus",
  "Aikut",
  "Aimas",
  "Aimasi/sp Iii Aimasi",
  "Aimau",
  "Aimere",
  "Aimere Timur",
  "Aimoli",
  "Ainamsato",
  "Ainan",
  "Ainani Tajriani",
  "Aindua",
  "Ainesa",
  "Ainesra",
  "Aing Bantai",
  "Ainiut",
  "Aipiri",
  "Air Abang",
  "Air Alun",
  "Air Amo",
  "Air Anyir",
  "Air Apo",
  "Air Asam",
  "Air Asuk",
  "Air Bajo",
  "Air Bakoman",
  "Air Balui",
  "Air Banai",
  "Air Bang",
  "Air Bara",
  "Air Baru",
  "Air Batang",
  "Air Batu",
  "Air Batu Buding",
  "Air Baus I",
  "Air Baus Ii",
  "Air Beliti",
  "Air Belo",
  "Air Bening",
  "Air Berau",
  "Air Bersih",
  "Air Berudang",
  "Air Besar",
  "Air Bikuk",
  "Air Bini",
  "Air Biru",
  "Air Buaya",
  "Air Bulan",
  "Air Bulin",
  "Air Buluh",
  "Air Cekdam",
  "Air Dekakah",
  "Air Dikit",
  "Air Dingin",
  "Air Dingin Baru",
  "Air Dingin Lama",
  "Air Dua",
  "Air Duku",
  "Air Duren",
  "Air Durian Jaya",
  "Air Emas",
  "Air Enau Upt Xi",
  "Air Gading",
  "Air Gantang",
  "Air Garam",
  "Air Gemuruh",
  "Air Genting",
  "Air Glubi",
  "Air Haji Barat",
  "Air Haji Tengah",
  "Air Haji Tenggara",
  "Air Hangat",
  "Air Hitam",
  "Air Hitam Besar",
  "Air Hitam Hulu",
  "Air Hitam Laut",
  "Air Itam",
  "Air Itam Timur",
  "Air Jamban",
  "Air Jelatang",
  "Air Jernih",
  "Air Joman",
  "Air Joman Baru",
  "Air Jukung",
  "Air Kalimat",
  "Air Kandis",
  "Air Kasai",
  "Air Kati",
  "Air Kelian",
  "Air Kelik",
  "Air Kelinsar",
  "Air Kemang",
  "Air Kemuning",
  "Air Kenari",
  "Air Kepala Tujuh",
  "Air Kering I",
  "Air Kering Ii",
  "Air Keruh",
  "Air Kopras",
  "Air Kotok",
  "Air Kuang",
  "Air Kubang",
  "Air Kumdang Bhakti",
  "Air Kumpai",
  "Air Kuning",
  "Air Kuti",
  "Air Lago",
  "Air Lanang",
  "Air Latak",
  "Air Lelangi",
  "Air Lengit",
  "Air Lesing",
  "Air Liki",
  "Air Liki Baru",
  "Air Limau",
  "Air Lingkar",
  "Air Lintang",
  "Air Long",
  "Air Mancur",
  "Air Mandidi",
  "Air Mangga",
  "Air Manis",
  "Air Mas",
  "Air Masin",
  "Air Mata",
  "Air Mati",
  "Air Mawar",
  "Air Mayan",
  "Air Melancar",
  "Air Meles Atas",
  "Air Meles Bawah",
  "Air Menduyung",
  "Air Menganyau",
  "Air Merah",
  "Air Merbau",
  "Air Molek I",
  "Air Molek Ii",
  "Air Mumu",
  "Air Mundu",
  "Air Muring",
  "Air Naningan",
  "Air Napal",
  "Air Nau",
  "Air Nona",
  "Air Nusa",
  "Air Nyatoh",
  "Air Nyuruk",
  "Air Pacah",
  "Air Padang",
  "Air Palawan",
  "Air Panas",
  "Air Panas Baru",
  "Air Pandan",
  "Air Pauh",
  "Air Payang",
  "Air Payangan",
  "Air Pedara",
  "Air Periukan",
  "Air Pesi",
  "Air Petai",
  "Air Pikat",
  "Air Pinang",
  "Air Puar",
  "Air Punggur",
  "Air Putih",
  "Air Putih Baru",
  "Air Putih Ilir",
  "Air Putih Kali Bandung",
  "Air Putih Lama",
  "Air Putih Ulu (c1,2)",
  "Air Raja",
  "Air Raman",
  "Air Rambai",
  "Air Rami",
  "Air Rengit / Pulau Muning",
  "Air Ringau",
  "Air Ringkih",
  "Air Ruai",
  "Air Rumbai",
  "Air Rupik",
  "Air Rusa",
  "Air Saga",
  "Air Salemba",
  "Air Salobar",
  "Air Santok",
  "Air Satan",
  "Air Sebakul",
  "Air Sebayur",
  "Air Sekamanak",
  "Air Selimang",
  "Air Selumar",
  "Air Sempiang",
  "Air Sena",
  "Air Senggeris",
  "Air Seru",
  "Air Sialang Hilir",
  "Air Sialang Hulu",
  "Air Sialang Tengah",
  "Air Simpang",
  "Air Solok Batu",
  "Air Sulau",
  "Air Suning",
  "Air Talas",
  "Air Tarap",
  "Air Tawar",
  "Air Tawar Barat",
  "Air Tawar Timur",
  "Air Teluh",
  "Air Teluk Hessa",
  "Air Temam",
  "Air Tenam",
  "Air Tenang",
  "Air Teras",
  "Air Terbit",
  "Air Terjun",
  "Air Ternate",
  "Air Tiris",
  "Air Umban",
  "Air Upas",
  "Airapa",
  "Airduren",
  "Airgegas",
  "Airkasar",
  "Airlakok",
  "Airlangga",
  "Airlimau",
  "Airmadidi Atas",
  "Airmadidi Bawah",
  "Airmesu",
  "Airmesu Timur",
  "Airoran",
  "Airterang",
  "Ais",
  "Aisa",
  "Aisandami",
  "Aisasior",
  "Aisau",
  "Aitinyo",
  "Aitiri",
  "Aitoun",
  "Aitrem",
  "Aiwat",
  "Ajai Siang",
  "Ajakkang",
  "Ajallasse",
  "Ajami",
  "Ajamu",
  "Ajang",
  "Ajang Laleng",
  "Ajang Pulu",
  "Ajangpulu",
  "Ajaobaki",
  "Ajee Cut",
  "Ajee Pagar Air",
  "Ajee Rayeuk",
  "Aji Baho",
  "Aji Jaya Knpi",
  "Aji Kagungan",
  "Aji Kuning",
  "Aji Mesir",
  "Aji Murni Jaya",
  "Aji Permai Talang Buah",
  "Ajibarang Kulon",
  "Ajibarang Wetan",
  "Ajibuhara",
  "Ajijahe",
  "Ajijulu",
  "Ajimbelang",
  "Ajinembah",
  "Ajjalireng",
  "Ajubissue",
  "Ajuen",
  "Ajung",
  "Ajuraja",
  "Aka-akae",
  "Akacipong",
  "Akah",
  "Akamar",
  "Akan Tapak",
  "Akang Siwah",
  "Akar",
  "Akar Akar",
  "Akar Bagantung Ulu",
  "Akar Baru",
  "Akas",
  "Akas Balane",
  "Akcaya",
  "Ake Daga",
  "Ake Jailolo",
  "Akeara",
  "Akedabo",
  "Akediri",
  "Akedotilou",
  "Akegula",
  "Akeguraci",
  "Akehuda",
  "Akeju",
  "Akekolano",
  "Akelaha",
  "Akelamo",
  "Akelamo Kao",
  "Akembawi",
  "Akenggen",
  "Akesai",
  "Akesibu",
  "Akesimbeka",
  "Aketernate",
  "Aketobololo",
  "Aketola",
  "Aketubatu",
  "Akhelaume",
  "Aki Jaya",
  "Akima",
  "Akkajeng",
  "Akkor",
  "Akkotengeng",
  "Akle",
  "Akmer",
  "Akmuri",
  "Ako",
  "Akomi",
  "Akoon",
  "Akoubaida",
  "Aksal",
  "Akudiomi",
  "Akul",
  "Akuni",
  "Al Kautsar",
  "Alaaha",
  "Alaang",
  "Aladadio",
  "Alah Air",
  "Alah Air Timur",
  "Alahan",
  "Alahan Kae",
  "Alahan Nan Tigo",
  "Alahan Panjang",
  "Alai",
  "Alai Gelombang",
  "Alai Parak Kopi",
  "Alai Selatan",
  "Alak",
  "Alakasing",
  "Alakaya",
  "Alaku",
  "Alala",
  "Alalak Padang",
  "Alalak Selatan",
  "Alalak Tengah",
  "Alalak Utara",
  "Alale",
  "Alam Buana",
  "Alam Jaya",
  "Alam Kenanga",
  "Alam Pakuan",
  "Alam Panjang",
  "Alam Pauh Duo",
  "Alam Pelita",
  "Alamendah",
  "Alang Alang",
  "Alang Alang Caruban",
  "Alang Alang Lebar",
  "Alang Asaude",
  "Alang Bonbon",
  "Alang Kepayang",
  "Alang Laweh",
  "Alangamba",
  "Alangga",
  "Alap Atadei",
  "Alas",
  "Alas Bangun",
  "Alas Bayur",
  "Alas Kandang",
  "Alas Kembang",
  "Alas Malang",
  "Alas Merancar",
  "Alas Mesikhat",
  "Alas Nyiur",
  "Alas Selatan",
  "Alas Tengah",
  "Alas Tlogo",
  "Alas Utara",
  "Alasan",
  "Alasan Nggolobuton",
  "Alasangker",
  "Alasbulu",
  "Alasdowo",
  "Alasgung",
  "Alaskokon",
  "Alasmalang",
  "Alasombo",
  "Alaspandan",
  "Alasraja",
  "Alasrejo",
  "Alassapi",
  "Alassumur",
  "Alassumur Kulon",
  "Alassumur Lor",
  "Alastengah",
  "Alastuwo",
  "Alaswangi",
  "Alat",
  "Alata Karya",
  "Alatengae",
  "Alatep",
  "Alausalo",
  "Aldom",
  "Alebo",
  "Aleleng",
  "Alemsom",
  "Alenangka",
  "Alengge Agung",
  "Alenggo",
  "Alesilurunge",
  "Alesipitto",
  "Aleuti",
  "Alewadeng",
  "Alewanuae",
  "Algadang",
  "Algonik",
  "Alhai",
  "Ali Aga",
  "Aliantan",
  "Aliduda",
  "Alila",
  "Alila Selatan",
  "Alila Timur",
  "Alim",
  "Alim Mebung",
  "Alimukim",
  "Alindau",
  "Alipato",
  "Alirji",
  "Alitta",
  "Alitupu",
  "Alius",
  "Aliyan",
  "Alkani",
  "Allaere",
  "Allakuang",
  "Allamungeng Patue",
  "Allang",
  "Alle Alle",
  "Allepolea",
  "Allesalewoe",
  "Alliritengae",
  "Allu Tarowang",
  "Allumang",
  "Alo",
  "Alo Utara",
  "Alo-alo",
  "Alobaga",
  "Aloban",
  "Alolama",
  "Alon-alon Contong",
  "Along",
  "Aloo",
  "Alooa",
  "Alopur",
  "Alor Besar",
  "Alor Kecil",
  "Alorawe",
  "Alosi",
  "Alosika",
  "Alu",
  "Aluan",
  "Aluan Besar",
  "Aluan Mati",
  "Aluan Sumur",
  "Alude",
  "Alue",
  "Alue Abee",
  "Alue Abet",
  "Alue Adan",
  "Alue Ambang",
  "Alue Anou Barat",
  "Alue Anou Timur",
  "Alue Awe",
  "Alue Bade",
  "Alue Bagok",
  "Alue Bakong",
  "Alue Barat",
  "Alue Baro",
  "Alue Baroh",
  "Alue Bata",
  "Alue Batee",
  "Alue Bateung Brook",
  "Alue Bayeu Utang",
  "Alue Berawe",
  "Alue Bie Pusong",
  "Alue Bieng",
  "Alue Bili",
  "Alue Bili Geulumpang",
  "Alue Bili Rayeuk",
  "Alue Bilie",
  "Alue Blang",
  "Alue Bu Alue Nireh",
  "Alue Bu Jalan",
  "Alue Bu Jalan Baroh",
  "Alue Bu Tuha",
  "Alue Bu Tunong",
  "Alue Bu/alue Lhok",
  "Alue Bugeng",
  "Alue Buket",
  "Alue Buloh",
  "Alue Buloh Dua",
  "Alue Buloh Satu",
  "Alue Bumban",
  "Alue Bungkoh",
  "Alue Buya",
  "Alue Buya Pasi",
  "Alue Calong",
  "Alue Campli",
  "Alue Canang",
  "Alue Cek Doy",
  "Alue Dalam",
  "Alue Dama",
  "Alue Dawah",
  "Alue Deah Teungoh",
  "Alue Dodok",
  "Alue Drien",
  "Alue Dua",
  "Alue Dua Bakaran Batee",
  "Alue Dua Muka 0",
  "Alue Dua Muka S",
  "Alue Dua Paya Gajah",
  "Alue Empeuk",
  "Alue Entok",
  "Alue Eumpok",
  "Alue Gadeng",
  "Alue Gadeng Satu",
  "Alue Gajah",
  "Alue Gampong",
  "Alue Gandai",
  "Alue Geudong",
  "Alue Geunteng",
  "Alue Geutah",
  "Alue Gintong",
  "Alue Glumpang",
  "Alue Gro",
  "Alue Gunto",
  "Alue Gurep",
  "Alue Ie Itam",
  "Alue Ie Mameh",
  "Alue Ie Mirah",
  "Alue Ie Puteh",
  "Alue Ie Tarek",
  "Alue Iet",
  "Alue Igeueh",
  "Alue Itam",
  "Alue Itam Baroh",
  "Alue Itam Reudeup",
  "Alue Jamok",
  "Alue Jampak",
  "Alue Jang",
  "Alue Jangat",
  "Alue Jerjak",
  "Alue Kambuek",
  "Alue Kaol",
  "Alue Keujruen",
  "Alue Keumang",
  "Alue Keumiki",
  "Alue Keumuneng",
  "Alue Keupula",
  "Alue Keureunyai",
  "Alue Keutapang",
  "Alue Kiran",
  "Alue Krak Kayee",
  "Alue Krueb",
  "Alue Krueng",
  "Alue Kumba",
  "Alue Kumbang A",
  "Alue Kumbang M",
  "Alue Kuta",
  "Alue Kuyuen",
  "Alue Kuyun",
  "Alue Labu",
  "Alue Lada",
  "Alue Lam Saba",
  "Alue Leuhob",
  "Alue Leukot",
  "Alue Lhee",
  "Alue Lhok",
  "Alue Lim",
  "Alue Limeng",
  "Alue Majron",
  "Alue Mangki",
  "Alue Mee",
  "Alue Merbau",
  "Alue Meuganda",
  "Alue Meuraksa",
  "Alue Meutuah",
  "Alue Mie",
  "Alue Mudem",
  "Alue Mulieng",
  "Alue Naga",
  "Alue Ngom",
  "Alue Nibong",
  "Alue Nyamuk",
  "Alue On",
  "Alue Padee",
  "Alue Panah",
  "Alue Pande",
  "Alue Pangkat",
  "Alue Panyang",
  "Alue Papeun",
  "Alue Patong",
  "Alue Perman",
  "Alue Peudeung",
  "Alue Peunawa",
  "Alue Peuno",
  "Alue Peusaja",
  "Alue Pineung",
  "Alue Pineung Timue",
  "Alue Pisang",
  "Alue Punti",
  "Alue Rambe",
  "Alue Rambong",
  "Alue Rambot",
  "Alue Rangan",
  "Alue Raya",
  "Alue Rayeuk",
  "Alue Rimei",
  "Alue Rindang",
  "Alue Riyeung",
  "Alue Sane",
  "Alue Selaseh",
  "Alue Sentang",
  "Alue Sepeng",
  "Alue Serdang",
  "Alue Seumambu",
  "Alue Seuralen",
  "Alue Seutui",
  "Alue Sijuek",
  "Alue Sikaya",
  "Alue Siron",
  "Alue Siwah Dua",
  "Alue Siwah Serdang",
  "Alue Sundak",
  "Alue Sungai Pinang",
  "Alue Tampak",
  "Alue Teh",
  "Alue Teungoh",
  "Alue Tho",
  "Alue Tuwi",
  "Alue Udep",
  "Alue Udeung",
  "Alue Unou",
  "Alue Wakie",
  "Aluh Aluh Kecil",
  "Aluh Aluh Kecil Muara",
  "Aluh-aluh Besar",
  "Alukuni",
  "Alul",
  "Alum Anggota",
  "Alun Alun",
  "Alun Dua",
  "Alunddua",
  "Alung Banua",
  "Aluppang",
  "Alur",
  "Alur Alim",
  "Alur Bandung",
  "Alur Baning",
  "Alur Baru",
  "Alur Baung",
  "Alur Bemban",
  "Alur Bujok",
  "Alur Buluh",
  "Alur Cantik",
  "Alur Cempedak",
  "Alur Cincin",
  "Alur Cucur",
  "Alur Drien",
  "Alur Dua",
  "Alur Dua Baru",
  "Alur Gading",
  "Alur Gadung",
  "Alur Jambu",
  "Alur Kejrun",
  "Alur Langsat",
  "Alur Lhok",
  "Alur Linci",
  "Alur Ludin I",
  "Alur Ludin Ii",
  "Alur Manis",
  "Alur Mas",
  "Alur Melati",
  "Alur Merbo",
  "Alur Nangka",
  "Alur Nunang",
  "Alur Pinang",
  "Alur Selalas",
  "Alur Selebu",
  "Alur Seuleumak",
  "Alur Simerah",
  "Alur Subur",
  "Alur Tani I",
  "Alur Tani Ii",
  "Alurduamas",
  "Alus Alus",
  "Alusi Batjas",
  "Alusi Buuk Jalin",
  "Alusi Kelaan",
  "Alusi Krawain",
  "Alusi Tamrian",
  "Alutbakon",
  "Amabaan",
  "Amadanom",
  "Amagais",
  "Amagarapati",
  "Amagatsu",
  "Amahai",
  "Amahusu",
  "Amaita",
  "Amaiteng Mulia",
  "Amakaka",
  "Amal",
  "Amal Bakti",
  "Amali Riattang",
  "Amaliah",
  "Amamapare",
  "Aman",
  "Aman Damai",
  "Aman Jaya",
  "Amanamkai",
  "Amandraya",
  "Amang",
  "Amansari",
  "Amar",
  "Amar Laut",
  "Amar Sakti",
  "Amarabu",
  "Amaroa",
  "Amarsekaru",
  "Amarwawatu",
  "Amasara",
  "Amase",
  "Amasing Kali",
  "Amasing Kota",
  "Amasing Kota Barat",
  "Amasing Kota Utara",
  "Amassangan",
  "Amassangang",
  "Amasu",
  "Amat",
  "Amat Selatan",
  "Amawang",
  "Amawang Kanan",
  "Amawang Kiri",
  "Amawang Kiri Muka",
  "Ambahai",
  "Ambai",
  "Ambai Atas",
  "Ambai Bawah",
  "Ambai Ii",
  "Ambaidiru",
  "Ambaipua",
  "Ambakiyang",
  "Ambakumina",
  "Ambal",
  "Ambal Ambil",
  "Ambalat",
  "Ambalkebrek",
  "Ambalkliwonan",
  "Ambalkumolo",
  "Ambalodangge",
  "Ambalresmi",
  "Ambalutu",
  "Amban",
  "Ambang I",
  "Ambang Ii",
  "Ambapa",
  "Ambar Halim",
  "Ambara",
  "Ambarang",
  "Ambarawa",
  "Ambarawa Barat",
  "Ambarawa Timur",
  "Ambarawang Darat",
  "Ambarawang Laut",
  "Ambarisan",
  "Ambarita",
  "Ambarjaya",
  "Ambarketawang",
  "Ambartawang",
  "Ambarwinangun",
  "Ambasang Natigor",
  "Ambason Mekar",
  "Ambat",
  "Ambawang",
  "Ambekaeri Utama",
  "Ambekairi",
  "Ambela",
  "Ambelang",
  "Ambender",
  "Ambeng Ambeng Watangrejo",
  "Ambengan",
  "Ambepulu",
  "Amber",
  "Amberi",
  "Amberparem/amperem",
  "Ambesaua",
  "Ambesea",
  "Ambesia",
  "Ambesia Barat",
  "Ambesia Selatan",
  "Ambesinauwi",
  "Ambesokoa",
  "Ambeua",
  "Ambeua Raya",
  "Ambia",
  "Ambia Utara",
  "Ambisu",
  "Ambit",
  "Ambit-mbit",
  "Ambobi Paranginan",
  "Ambok",
  "Ambokembang",
  "Ambokulon",
  "Ambololi",
  "Ambondia",
  "Amboniki",
  "Ambopadang",
  "Ambopi",
  "Ambora",
  "Amboran",
  "Amborep",
  "Amborgang",
  "Amborokan Pane Raya",
  "Ambowetan",
  "Amboyo Inti",
  "Amboyo Selatan",
  "Amboyo Utara",
  "Ambroben",
  "Ambu Ulanu",
  "Ambuar",
  "Ambuau Indah",
  "Ambuau Togo",
  "Ambukha",
  "Ambulu",
  "Ambumi",
  "Ambungan",
  "Ambunten Barat",
  "Ambunten Tengah",
  "Ambunten Timur",
  "Ambunu",
  "Ambutun",
  "Ambuwiu",
];
